version: "3.7"

services:
  postgres:
    container_name: ${postgres_container_name}
    hostname: ${postgres_host_name}
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${postgres_db}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
    ports:
      - ${postgres_host_port}:${postgres_container_port}
    volumes:
      - modules_data:/var/lib/postgresql/data
      - ./database-init/init-modules.sql:/docker-entrypoint-initdb.d/init-modules.sql
    networks:
      - modules_network

volumes:
  modules_data:
    driver: local

networks:
  modules_network:
    driver: bridge
    name: modules_network