package de.ruu.lab.modules.shop.ui.fx.item;

import de.ruu.lib.fx.comp.FXCViewService;

/**
 * {@link ItemService} application service
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2022.12.23 18:14:58:657
 */
public interface ItemService extends FXCViewService
{ }