package de.ruu.lab.modules.shop.ui.fx.item;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * FXComp component {@link Item}
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2022.12.23 18:14:58:656
 */
public class Item extends DefaultFXCView 
{ }