package de.ruu.lab.modules.shop.ui.fx.item;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * {@link ItemAppRunner} application runner
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2022.12.23 18:14:58:661
 */
@Slf4j
public class ItemAppRunner extends FXCAppRunner 
{
	public static void main(String[] args)
	{
		log.debug("starting " + ItemApp.class.getName());
		FXCAppRunner.run(ItemApp.class, args);
		log.debug("finished " + ItemApp.class.getName());
	}
}