package de.ruu.lab.modules.shop.ui.fx.item;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * {@link ItemApp} application
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2022.12.23 18:14:58:660
 */
public class ItemApp extends FXCApp 
{ }