package de.ruu.lab.modules.shop.ui.fx.catalog;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * FXComp component {@link Catalog}
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2022.12.23 18:14:58:641
 */
public class Catalog extends DefaultFXCView 
{ }