package de.ruu.lab.modules.shop.ui.fx.catalog;

import de.ruu.lib.fx.comp.FXCViewService;

/**
 * {@link CatalogService} application service
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2022.12.23 18:14:58:642
 */
public interface CatalogService extends FXCViewService
{ }