package de.ruu.lab.modules.shop.ui.fx.catalog;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * {@link CatalogAppRunner} application runner
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2022.12.23 18:14:58:648
 */
@Slf4j
public class CatalogAppRunner extends FXCAppRunner 
{
	public static void main(String[] args)
	{
		log.debug("starting " + CatalogApp.class.getName());
		FXCAppRunner.run(CatalogApp.class, args);
		log.debug("finished " + CatalogApp.class.getName());
	}
}