package de.ruu.lab.modules.shop.ui.fx.catalog;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * {@link CatalogApp} application
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2022.12.23 18:14:58:646
 */
public class CatalogApp extends FXCApp 
{ }