package de.ruu.lab.modules.shop.ui.fx.catalog;

import de.ruu.lib.fx.comp.DefaultFXCViewController;
import javafx.fxml.FXML;

/**
 * {@link CatalogController} application controller
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2022.12.23 18:14:58:643
 */
public class CatalogController extends DefaultFXCViewController 
{
	@Override
	@FXML
	protected void initialize(){
		// TODO generated method stub
	}
}