package de.ruu.lab.modules.shop.ui.fx.order;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * {@link OrderAppRunner} application runner
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2022.12.23 18:14:58:666
 */
@Slf4j
public class OrderAppRunner extends FXCAppRunner 
{
	public static void main(String[] args)
	{
		log.debug("starting " + OrderApp.class.getName());
		FXCAppRunner.run(OrderApp.class, args);
		log.debug("finished " + OrderApp.class.getName());
	}
}