package de.ruu.lab.modules.shop.ui.fx.order;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * FXComp component {@link Order}
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2022.12.23 18:14:58:662
 */
public class Order extends DefaultFXCView 
{ }