package de.ruu.lab.modules.shop.ui.fx.order;

import de.ruu.lib.fx.comp.FXCViewService;

/**
 * {@link OrderService} application service
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2022.12.23 18:14:58:663
 */
public interface OrderService extends FXCViewService
{ }