package de.ruu.lab.modules.shop.ui.fx.order;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * {@link OrderApp} application
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2022.12.23 18:14:58:665
 */
public class OrderApp extends FXCApp 
{ }