package de.ruu.lab.modules.shop.ui.fx.order;

import de.ruu.lib.fx.comp.DefaultFXCViewController;
import javafx.fxml.FXML;

/**
 * {@link OrderController} application controller
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2022.12.23 18:14:58:664
 */
public class OrderController extends DefaultFXCViewController 
{
	@Override
	@FXML
	protected void initialize(){
		// TODO generated method stub
	}
}