package de.ruu.lab.modules.shop.ui.fx;

import de.ruu.lib.fx.comp.FXCViewService;

/**
 * {@link ShopService} application service
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2022.12.23 18:14:58:204
 */
public interface ShopService extends FXCViewService
{ }