package de.ruu.lab.modules.shop.ui.fx;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * {@link ShopApp} application
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2022.12.23 18:14:58:540
 */
public class ShopApp extends FXCApp { }