package de.ruu.lab.modules.shop.ui.fx;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * FXComp component {@link Shop}
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2022.12.23 18:14:58:004
 */
public class Shop extends DefaultFXCView 
{ }