package de.ruu.lab.modules.shop.ui.fx;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * {@link ShopAppRunner} application runner
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2022.12.23 18:14:58:549
 */
@Slf4j
public class ShopAppRunner extends FXCAppRunner 
{
	public static void main(String[] args)
	{
		log.debug("starting " + ShopApp.class.getName());
		FXCAppRunner.run(ShopApp.class, args);
		log.debug("finished " + ShopApp.class.getName());
	}
}