package de.ruu.lab.modules.shop.ui.fx.inventory;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * FXComp component {@link Inventory}
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2022.12.23 18:14:58:649
 */
public class Inventory extends DefaultFXCView 
{ }