package de.ruu.lab.modules.shop.ui.fx.inventory;

import de.ruu.lib.fx.comp.FXCViewService;

/**
 * {@link InventoryService} application service
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2022.12.23 18:14:58:650
 */
public interface InventoryService extends FXCViewService
{ }