package de.ruu.lab.modules.shop.ui.fx.inventory;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * {@link InventoryApp} application
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2022.12.23 18:14:58:654
 */
public class InventoryApp extends FXCApp 
{ }