package de.ruu.lab.modules.shop.ui.fx.inventory;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * {@link InventoryAppRunner} application runner
 * <p>
 * generated by {@link de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2022.12.23 18:14:58:654
 */
@Slf4j
public class InventoryAppRunner extends FXCAppRunner 
{
	public static void main(String[] args)
	{
		log.debug("starting " + InventoryApp.class.getName());
		FXCAppRunner.run(InventoryApp.class, args);
		log.debug("finished " + InventoryApp.class.getName());
	}
}